name: www
description: "Blood donation app built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10

  # Utilities
  intl: ^0.19.0
  intl_phone_field: ^3.1.0
  shared_preferences: ^2.5.5
  logger: ^2.3.0

  # State Management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # App Icon Generator
  flutter_launcher_icons: ^0.14.4

  flutter_native_splash: ^2.4.0


# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"


flutter_native_splash:
  color: "#000000"
  android_12:
    color: "#000000"


flutter:
  uses-material-design: true

  assets:
    - assets/blood_3728510.png
    - assets/world-blood-donor-day.png
    - assets/screen.png

  # Example for future fonts (optional)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf