// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqHvyDua59_zqPsHRMOSRA-0hTtodkzyU',
    appId: '1:789508094699:web:26d383d0ed99c036b69cae',
    messagingSenderId: '789508094699',
    projectId: 'bloodlink-83cb8',
    authDomain: 'bloodlink-83cb8.firebaseapp.com',
    storageBucket: 'bloodlink-83cb8.firebasestorage.app',
    measurementId: 'G-ZBSY8WMQX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0_DIIK7C0LKUTSWpKNoTv6kMZVIAn658',
    appId: '1:789508094699:android:d2ce3121794a44fcb69cae',
    messagingSenderId: '789508094699',
    projectId: 'bloodlink-83cb8',
    storageBucket: 'bloodlink-83cb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvxuV74hQFmASnXZVjTFgpXHZUvZ31voU',
    appId: '1:789508094699:ios:99e4f3af30ee054bb69cae',
    messagingSenderId: '789508094699',
    projectId: 'bloodlink-83cb8',
    storageBucket: 'bloodlink-83cb8.firebasestorage.app',
    iosBundleId: 'com.example.www',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvxuV74hQFmASnXZVjTFgpXHZUvZ31voU',
    appId: '1:789508094699:ios:99e4f3af30ee054bb69cae',
    messagingSenderId: '789508094699',
    projectId: 'bloodlink-83cb8',
    storageBucket: 'bloodlink-83cb8.firebasestorage.app',
    iosBundleId: 'com.example.www',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqHvyDua59_zqPsHRMOSRA-0hTtodkzyU',
    appId: '1:789508094699:web:8fd7e9129b314097b69cae',
    messagingSenderId: '789508094699',
    projectId: 'bloodlink-83cb8',
    authDomain: 'bloodlink-83cb8.firebaseapp.com',
    storageBucket: 'bloodlink-83cb8.firebasestorage.app',
    measurementId: 'G-HMFS8DKWKN',
  );
}
